name: Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml

      
  run_test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Run Tests
      run: mvn test
      
  telegram:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run tests
      run: |
        # Здесь запускаются ваши тесты

    - name: Send Telegram notification
      run: |
        curl -s -X POST https://api.telegram.org/bot{7030422177:AAFQVnnOg3GmPqOtDJjFpSsKzfm2bIE5G_w}/sendMessage -d chat_id={1399351264} -d text="Тесты прошли успешно!"
