name: Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml

      
  run_test:
  
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Run Tests
      run: mvn test
    - name: Send Telegram notification
      if: ${{ failure() }}
      uses: appleboy/telegram-action@v2
      with:
        to: ${{ secrets.1399351264 }}
        token: ${{ secrets.7030422177:AAFQVnnOg3GmPqOtDJjFpSsKzfm2bIE5G_w }}
        message: |
          ❌ Tests have failed! See details below:

          ${{ job.status }}

          The failing test is:
          ${{ job.status }}
     
